version: '3.9'

services:
  go-app:
    container_name: go-app
    image: varx/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=mysecret dbname=testdb sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}